plugins {
    id 'java-library'
    id 'org.springframework.boot' version '3.1.1'
    id 'io.spring.dependency-management' version '1.1.4'
}

bootJar {
    enabled(false)
}

allprojects {
    group = 'com.monglife.discovery'
    version = '2.1.0'

    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
    }
}