dependencies {
    // Firebase Admin SDK
    implementation 'com.google.firebase:firebase-admin:9.2.0'
}

tasks.register('copyPrivate', Copy) {
    copy {
        from '../../configs/clients/monglife-discovery-client-fcm/'
        include '*.yml'
        into 'src/main/resources'
    }

    copy {
        from '../../configs/clients/monglife-discovery-client-fcm/'
        include '*.json'
        into 'src/main/resources'
    }
}