dependencies {
    // monglife-jpa
    implementation "com.github.monglife.monglife-module-common:monglife-module-common-jpa:${monglifeModuleCommonVersion}"

    // mysql
    runtimeOnly "com.mysql:mysql-connector-j"

    // queryDSL
    implementation "com.querydsl:querydsl-jpa:5.0.0:jakarta"
    annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties["querydsl.version"]}:jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"
}