dependencies {
    // spring
    implementation "org.springframework.cloud:spring-cloud-starter-netflix-eureka-server"
    implementation "org.springframework.boot:spring-boot-starter-web"

    // prometheus
    implementation "org.springframework.boot:spring-boot-starter-actuator:${acuatorVersion}"
    runtimeOnly "io.micrometer:micrometer-registry-prometheus"
}